### ISSUE TITLE
Command line argument --test

### ISSUE THREAD

**Issue by jose** [SpoonLabs/npefix#19]
Hi,

As defined in section [Command line](https://github.com/SpoonLabs/npefix#command-line), `--test` is the "failing_test". Is this "failing_test" a test class or a test case/method? Does `--test` support more than one? If so, how? And, should failing and non-failing tests be provided, or just failing tests?

--
Best,
Jose

**Comment by tdurieux** [comment]
--test Define the test classes of the project, fully-qualified, separated with ':' 

NPEfix will automatically extract the test methods.

**Comment by jose** [comment]
Ok, thanks @tdurieux.
