### ISSUE TITLE
How does NPEFix validate the candidate patches?

### ISSUE THREAD

**Issue by DehengYang** [SpoonLabs/npefix#22]
Sorry for disturbing you with this issue. I am interested in the NPEFix that is a good APR technique and also integrated into RepairThemAll.  I now would like to ask for your help and guidance on the way of NPEFix to validate a candidate patch.

For example, does it firstly re-compile the candidate patch, and then run failing tests, and finally run all positive tests or all test cases?

It would be sincerely appreciated if any help could be provided.

Thank you in advance for your time and help!

**Comment by monperrus** [comment]
> For example, does it firstly re-compile the candidate patch, and then run failing tests, and finally run all positive tests or all test cases?

It does run the failing tests, but not the passing ones.

Note that it does not "recompile" the program per se, because everything is done with metaprogramming.

**Comment by DehengYang** [comment]
Thank you so much for so prompt reply and kind help! May I ask a further question: so would it possibly break the functionality if it does not run passing ones?

Thanks agains for your help!

**Comment by monperrus** [comment]
> so would it possibly break the functionality if it does not run passing ones?

In theory yes, if a passing test throws and catches an NPE, and breaks if the NPE is not thrown anymore. In practice, this is very very rare.

**Comment by DehengYang** [comment]
Thank you for the detailed explanation. My doubt is perfectly solved with your kind help.  

Thanks!
